import type { Project, Task, Workspace } from "@/server/db/schema";

const createdAt = new Date("2026-05-11T07:00:00Z");

export const demoWorkspace: Workspace = {
  slug: "tasks",
  name: "studio. shipping log",
  description: "What we're building next, written in plain English.",
  ownerUserId: "seed-demo-user",
  plan: "free",
  createdAt,
  updatedAt: createdAt,
};

export const demoProjects: Project[] = [
  {
    workspaceSlug: "tasks",
    slug: "product",
    name: "Product Roadmap",
    oneLiner: "What we're building — and what we said no to.",
    accent: "#4f46e5",
    sortOrder: 0,
    shareToken: null,
    isPublic: true,
  },
];

export const demoTasks: Task[] = [
  {
    id: "tasks-product-001",
    projectSlug: "product",
    workspaceSlug: "tasks",
    title: "Workspace onboarding — paste your markdown",
    description:
      "First-run experience for new workspaces. Paste a markdown roadmap, we parse it into structured items. Zero forms, zero dropdowns.",
    status: "in-flight",
    phase: null,
    tier: null,
    assignee: "claude-code",
    cycleLabel: null,
    targetDate: "2026-05-14",
    sortOrder: 1,
    kind: "cycle",
    category: null,
    priority: null,
    blockerId: null,
    unblocks: null,
    weekHeading: null,
    channel: null,
    isLaunch: false,
    day: null,
    postingTime: null,
    createdAt,
    updatedAt: createdAt,
    completedAt: null,
  },
  {
    id: "tasks-product-002",
    projectSlug: "product",
    workspaceSlug: "tasks",
    title: "Proof card on the marketing homepage",
    description:
      "A live screenshot of the demo workspace embedded in the homepage hero — so the product sells itself without a separate demo page. Blocked on screenshot infra.",
    status: "blocked",
    phase: null,
    tier: null,
    assignee: "claude-code",
    cycleLabel: null,
    targetDate: "2026-05-15",
    sortOrder: 2,
    kind: "cycle",
    category: null,
    priority: null,
    blockerId: null,
    unblocks: null,
    weekHeading: null,
    channel: null,
    isLaunch: false,
    day: null,
    postingTime: null,
    createdAt,
    updatedAt: createdAt,
    completedAt: null,
  },
  {
    id: "tasks-product-003",
    projectSlug: "product",
    workspaceSlug: "tasks",
    title: "Invite-only beta",
    description:
      "Gated signup behind an invite code. Small cohort, high-signal feedback. No public self-serve until the onboarding is solid.",
    status: "in-flight",
    phase: null,
    tier: null,
    assignee: "claude-code",
    cycleLabel: null,
    targetDate: "2026-05-18",
    sortOrder: 3,
    kind: "cycle",
    category: null,
    priority: null,
    blockerId: null,
    unblocks: null,
    weekHeading: null,
    channel: null,
    isLaunch: false,
    day: null,
    postingTime: null,
    createdAt,
    updatedAt: createdAt,
    completedAt: null,
  },
  {
    id: "tasks-product-004",
    projectSlug: "product",
    workspaceSlug: "tasks",
    title: "Shared comment threads on roadmap items",
    description:
      "People who need the plan can leave comments on individual roadmap items. Auth-gated for writes; public for reads. Keeps the conversation in context.",
    status: "in-flight",
    phase: null,
    tier: null,
    assignee: "claude-code",
    cycleLabel: null,
    targetDate: "2026-05-21",
    sortOrder: 4,
    kind: "cycle",
    category: null,
    priority: null,
    blockerId: null,
    unblocks: null,
    weekHeading: null,
    channel: null,
    isLaunch: false,
    day: null,
    postingTime: null,
    createdAt,
    updatedAt: createdAt,
    completedAt: null,
  },
  {
    id: "tasks-product-005",
    projectSlug: "product",
    workspaceSlug: "tasks",
    title: "Composite-PK multi-tenancy",
    description:
      'Project slugs are now scoped per workspace — two teams can each have a project called "blog" without colliding. Schema migration shipped cleanly.',
    status: "shipped",
    phase: null,
    tier: null,
    assignee: "claude-code",
    cycleLabel: null,
    targetDate: "2026-05-08",
    sortOrder: 5,
    kind: "cycle",
    category: null,
    priority: null,
    blockerId: null,
    unblocks: null,
    weekHeading: null,
    channel: null,
    isLaunch: false,
    day: null,
    postingTime: null,
    createdAt,
    updatedAt: createdAt,
    completedAt: new Date("2026-05-08T09:00:00Z"),
  },
  {
    id: "tasks-product-006",
    projectSlug: "product",
    workspaceSlug: "tasks",
    title: "studio. brand integration in nav + footer",
    description:
      "The studio. parent brand whisper is now in the nav and footer — links Tasks and Roadmap under one roof without making it a big deal.",
    status: "shipped",
    phase: null,
    tier: null,
    assignee: "claude-code",
    cycleLabel: null,
    targetDate: "2026-05-10",
    sortOrder: 6,
    kind: "cycle",
    category: null,
    priority: null,
    blockerId: null,
    unblocks: null,
    weekHeading: null,
    channel: null,
    isLaunch: false,
    day: null,
    postingTime: null,
    createdAt,
    updatedAt: createdAt,
    completedAt: new Date("2026-05-10T09:00:00Z"),
  },
  {
    id: "tasks-product-007",
    projectSlug: "product",
    workspaceSlug: "tasks",
    title: "AI-generated roadmap items",
    description:
      "Not this year. The product's value is structured clarity, not generated content. If we ship AI suggestions before the manual workflow is proven, we're solving the wrong problem.",
    status: "refused",
    phase: null,
    tier: null,
    assignee: "claude-code",
    cycleLabel: null,
    targetDate: null,
    sortOrder: 7,
    kind: "refusal",
    category: null,
    priority: null,
    blockerId: null,
    unblocks: null,
    weekHeading: null,
    channel: null,
    isLaunch: false,
    day: null,
    postingTime: null,
    createdAt,
    updatedAt: createdAt,
    completedAt: null,
  },
];

export const demoUpcomingTasks = demoTasks.filter(
  (task) => task.status !== "shipped" && task.status !== "refused",
);
